export const CHANGE_PLAYMUSIC = 'CHANGE_PLAYMUSIC';
export const CHANGE_PLAYLIST = 'CHANGE_PLAYLIST';
export const CHANGE_CURRENTINDEX = 'CHANGE_CURRENTINDEX';

export const CHANGE_LYRIC_LIST = "player/CHANGE_LYRIC_LIST";
export const CHANGE_CURRENT_LYRIC_INDEX = "player/CHANGE_CURRENT_LYRIC_INDEX";