export const CHANGE_RECOMMEND = 'CHANGE_RECOMMEND'
export const CHANGE_HOTRECOMMEDN = 'CHANGE_HOTRECOMMEDN'
export const CHANGE_NEW_ALBUM = 'CHANGE_NEW_ALBUM'
export const CHANGE_RANKLIST0 = 'CHANGE_RANKLIST0'
export const CHANGE_RANKLIST1 = 'CHANGE_RANKLIST1'
export const CHANGE_RANKLIST2 = 'CHANGE_RANKLIST2'
export const CHANGE_SETTLE_SONGER = "recommend/CHANGE_SETTLE_SONGER";